### ISSUE TITLE
Memory leak due to excessive memoization

### ISSUE THREAD

**Issue by iskandr** [openvax/varcode#156]
See: https://github.com/hammerlab/pyensembl/issues/150

**Comment by iskandr** [comment]
I let Varcode run up about 1gb of memory doing effect prediction and then checked out the most allocated objects with [objgraph](https://www.huyng.com/posts/python-performance-analysis).

```
list                       853298
weakproxy                  360369
_Link                      360369
tuple                      313762
dict                       300230
OrderedDict                90092
Exon                       46690
Variant                    45124
function                   26384
Transcript                 14879
```

**Comment by iskandr** [comment]
We get a slightly different summary from [pympler](https://pythonhosted.org/Pympler/muppy.html) but in either case I'm not sure how these objects can add up to >1gb. 

```
                             <class 'dict |      300318 |    126.16 MB
          <class 'collections.OrderedDict |       90092 |    112.04 MB
                              <class 'str |      748295 |     87.50 MB
                             <class 'list |      853389 |     82.99 MB
                        <class 'weakproxy |      360369 |     27.49 MB
                <class 'collections._Link |      360369 |     24.74 MB
                            <class 'tuple |      309318 |     24.59 MB
          <class 'varcode.variant.Variant |       45124 |      7.92 MB
                              <class 'int |      264699 |      7.09 MB
                             <class 'code |       24390 |      3.35 MB
                            <class 'float |      135719 |      3.11 MB
                             <class 'type |        2917 |      2.94 MB
              <class 'pyensembl.exon.Exon |       46690 |      2.49 MB
                              <class 'set |        2269 |    979.34 KB
  <class 'pyensembl.transcript.Transcript |       14879 |    813.70 KB
```

**Comment by timodonnell** [comment]
Random thought... might consider a caching/memoization library with support for expiration like joblib http://pythonhosted.org/joblib/

**Comment by hammer** [comment]
If we are going to do surgery here I'd rather see us push more logic down to the database rather than making our application-layer logic ever more arcane.

**Comment by iskandr** [comment]
@hammer So far I'm focusing on lifting memoization where it's not needed, so hopefully making the code less rather than more arcane. Eager to hear suggestions about which parts might be easily pushed into the database.

**Comment by iskandr** [comment]
@timodonnell It looks like the joblib memoization is specifically for writing results out to disk.

**Comment by iskandr** [comment]
Old PR fixed this as much as I think is worth any effort: https://github.com/openvax/varcode/pull/157
