### ISSUE TITLE
Optionally serialize VCF + annotations to a new VCF

### ISSUE THREAD

**Issue by hammer** [openvax/varcode#18]
Annotations should follow the [ANN standard](http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf).

**Comment by iskandr** [comment]
I think serializing to VCF is possible without any of the annotation but following an external standard seems like a big endeavor.

**Comment by iskandr** [comment]
We have basic VCF serialization but serializing the annotations into any standard annotation format  will probably never happen.
