### ISSUE TITLE
Variants before and over the stop codon lose information.

### ISSUE THREAD

**Issue by joaoe** [openvax/varcode#202]
Howdy.

Testcase, over transcript ENSMUST00000086738, GRCm38
```
chr1 100484693 . TTCATCTGA CCC
```
The end of that transcript looks like
```
TTC ATC TGA ACT
 F   I   *   T
```
and this mutation will cause the location plus downstream to become
```
PTIVWSSGPLF(...)
```
The annotation that varcode gives is
```
StopLoss
* aa_mutation_start_offset = 1292
* aa_ref="*"
* aa_alt="PTIVWSS(...)"
```
It should actually be
```
StopLoss
* aa_mutation_start_offset = 1290
* aa_ref="FI*"
* aa_alt="PTIVWSS(...)"
```
The main issue is that even though `aa_ref` could be disregarded, `aa_mutation_start_offset` and `aa_alt` are desynchronized, since `aa_alt` actually starts two AAs upstream.

My suggestion is just to add `start, aa_ref, aa_alt`to the constructor of `StopLoss`like all other variants. `PrematureStop`is also about fiddling with stop codons and it contains those properties.

**Comment by iskandr** [comment]
Good catch! Thanks for continuing to come up with good test cases.

**Comment by iskandr** [comment]
Fixed by https://github.com/openvax/varcode/pull/203/files
