### ISSUE TITLE
varcode on Windows throws error: ImportError: No module named 'resource'

### ISSUE THREAD

**Issue by 229668880** [openvax/varcode#234]
Google says this is because resource module doesn't support Windows. Does it mean I should give up using varcode on Windows?

I am using Python 3.5. on Windows. I used pip3 to install varcode.

**Comment by iskandr** [comment]
Hey @229668880 --- none of the developers use Windows, so it might be that Varcode doesn't work. 
Can you post a full stack trace? I'm curious where this library is getting imported.

**Comment by iskandr** [comment]
My suspicion is that this comes from `gtfparse.util`, which is only using `resource` to get the available memory. 

@julia326 -- we should change that to be more portable

**Comment by iskandr** [comment]
@229668880  -- once we push a new version of gtfparse (https://github.com/openvax/gtfparse) then varcode should work on Windows.

**Comment by 229668880** [comment]
Thanks. I just got the reason. I should use pip install python-resource, not pip install resource.  python-resource is windows version of resource.
