### ISSUE TITLE
Incorrect result (and fix) in effect_ordering.py

### ISSUE THREAD

**Issue by LouieKam** [openvax/varcode#238]
I stumbled across several instances where top_priority_effect() would not return the highest priority effect. I fixed this issue with the following modifications to keep_max_priority_effects and filter_pipeline, respectively:

line 345
`priority_values = tuple(map(effect_priority, effects))`

lines 409-415
```
for filter_fn in filters:
        if len(effects) == 1:
            return effects
        filtered_effects = filter_fn(effects)
        if len(filtered_effects) > 0:
            effects = filtered_effects
    return effects
```

**Comment by iskandr** [comment]
I guess not shocking that the code I recently changed had a mistake. 

Let me compare your version with what's there.

**Comment by iskandr** [comment]
D'oh, Python3 `map` doesn't return a list anymore...

```priority_values = tuple(map(effect_priority, effects))```

**Comment by iskandr** [comment]
Fixed, thank you for pointing it out!
