### ISSUE TITLE
Update varcode in PyPI

### ISSUE THREAD

**Issue by jonasscheid** [openvax/varcode#249]
Hey there! As already described in #247 we are also having troubles with pyvcf. I see you changed from pyvcf to pyvcf3. However if I install varcode via pip, I still end up getting the "old" pyvcf. Could that be that there is an old version on PyPI that still has pyvcf in the required packages instead of pyvcf3?
If yes, are you willing to update it in the near future?

**Comment by iskandr** [comment]
Hey @jonasscheid -- sorry to let this hang for so long (it's been confusing maintaining these packages after switching jobs). I just uploaded Varcode 1.1.0 to PyPI, let me know if that fixes things for you.

**Comment by jonasscheid** [comment]
Hey @iskandr! Thanks for the quick response! Great, that helped. Glad that it went so fast 🙏
